version: '3.7'

services:
  cilium:
    image: docker.io/cilium/cilium:v1.9.3
    command: cilium-agent --ipv4-range ${KITT_NETWORK} --kvstore consul --kvstore-opt consul.address=${CONSUL_IP}:8500 --enable-ipv6=false --enable-hubble=false --enable-policy=default --ipv4-node=${NODE_IP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/docker/netns:/var/run/docker/netns
      - /sys/fs/bpf:/sys/fs/bpf
      - ./etc/data/cilium:/var/run/cilium
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"
      - "SYS_ADMIN"
    privileged: true
    restart: always
  plugin:
    image: docker.io/cilium/docker-plugin:v1.9.3
    command: cilium-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/docker/plugins:/run/docker/plugins
      - ./etc/data/cilium:/var/run/cilium
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    privileged: true
    depends_on:
      - cilium
    restart: always
