version: '3.7'

services:
  cilium:
    image: defn/cilium
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/docker/netns:/var/run/docker/netns
      - /sys/fs/bpf:/sys/fs/bpf
      - ${CILIUM_MOUNT:-./mnt}/cilium:/var/run/cilium
      - env_cilium:/secrets
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"
      - "SYS_ADMIN"
    privileged: true
    restart: always
  plugin:
    image: defn/cilium-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/docker/plugins:/run/docker/plugins
      - ${CILIUM_MOUNT:-./mnt}/cilium:/var/run/cilium
    network_mode: "host"
    cap_add:
      - "NET_ADMIN"
    privileged: true
    depends_on:
      - cilium
    restart: always

volumes:
  env_cilium:
    external: true
